apiVersion: v1
kind: Service
metadata:
  name: first-kube
  namespace: default
spec:
  selector:
    app: first-kube
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
  type: LoadBalancer
